In [128]:
from __future__ import print_function  # Python 2 and 3
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
from scipy import stats
import pandas as pd
%matplotlib inline
plt.style.use('ggplot')
pd.set_option('display.max_rows', 80)
pd.set_option('display.max_columns', 80)


In [129]:
data = pd.read_csv('to_model.csv', index_col=0)
test = pd.read_csv('to_test.csv', index_col=0)

In [130]:
set(data.columns) - set(test.columns)
#set(test.columns) - set(data.columns)

{'Exterior1st_ImStucc',
 'Exterior1st_Stone',
 'Exterior2nd_Other',
 'HouseStyle_2.5Fin',
 'SalePrice'}

In [131]:
concat = pd.concat([data,test], axis=0, ignore_index=False, sort=False).fillna(0)
#len(data)
df_trainingset = concat[:1445]
df_testingset = concat[1445:]
df_testingset = df_testingset.drop('SalePrice', axis = 1)


In [196]:
df_trainingset

LotFrontage    LotArea  OverallQual  YearBuilt  YearRemodAdd  \
Id                                                                   
1       15.287695  13.632926            7          5             5   
2       17.239974  13.910482            6         31            31   
3       15.693788  14.259735            7          7             6   
4       14.590868  13.899064            7         91            36   
5       17.730821  14.790720            8          8             8   
...           ...        ...          ...        ...           ...   
1456    14.872738  13.492362            6          8             7   
1457    17.851808  14.612288            6         32            22   
1458    15.424015  13.779845            7         69             4   
1459    15.693788  13.936991            5         60            14   
1460    16.609928  13.986054            5         43            43   

      MasVnrArea  BsmtUnfSF  TotalBsmtSF  1stFlrSF  2ndFlrSF  GrLivArea  \
Id                                                                        
1       2.984793  20.432408   305.810785  7.304664  4.518654  10.545150   
2       0.000000  28.298505   420.481939  7.759475  0.000000   9.965541   
3       2.930671  35.002689   324.450218  7.388824  4.524517  10.629408   
4       0.000000  39.018542   276.167375  7.439786  4.466991  10.553052   
5       3.135307  37.181717   388.234879  7.645087  4.605592  11.036133   
...          ...        ...          ...       ...       ...        ...   
1456    0.000000  51.618295   333.968531  7.430011  4.430243  10.472678   
1457    2.837770  40.733370   495.565378  8.347088  0.000000  10.920641   
1458    0.000000  49.557574   390.180479  7.688400  4.642183  11.160285   
1459    0.000000   0.000000   369.501083  7.574327  0.000000   9.671017   
1460    0.000000  19.422098   418.841861  7.753866  0.000000   9.956574   

      TotRmsAbvGrd  Fireplaces  GarageYrBlt  GarageCars  GarageArea  \
Id                                                                    
1                8           0          5.0         2.0  209.085751   
2                6           1         31.0         2.0  181.157116   
3                6           1          7.0         2.0  227.650453   
4                7           1          8.0         3.0  238.019376   
5                9           1          8.0         3.0  295.420207   
...            ...         ...          ...         ...         ...   
1456             7           1          8.0         2.0  181.157116   
1457             7           2         32.0         2.0  193.963719   
1458             9           2         69.0         1.0  110.579060   
1459             5           0         60.0         1.0  106.234773   
1460             6           0         43.0         1.0  119.156104   

      WoodDeckSF  OpenPorchSF  SalePrice  TotalFinishedBsmt  TotalBath  \
Id                                                                       
1       0.000000     4.202979   208500.0          16.356022        3.5   
2       4.612728     0.000000   181500.0          18.058681        2.5   
3       0.000000     3.824124   223500.0          14.566479        3.5   
4       0.000000     3.640608   140000.0          11.206217        2.0   
5       4.325850     4.530618   250000.0          15.983303        3.5   
...          ...          ...        ...                ...        ...   
1456    0.000000     3.774904   175000.0           0.000000        2.5   
1457    4.713592     0.000000   210000.0          17.918325        3.0   
1458    0.000000     4.186119   266500.0          12.137099        2.0   
1459    4.743728     0.000000   142125.0          18.594457        2.0   
1460    5.174264     4.313959   147500.0          18.808348        2.5   

      LotShape_IR2  LotShape_IR3  LotShape_Reg  Neighborhood_BrDale  \
Id                                                                    
1                0             0             1                    0   
2                0 

# Multilinear Regression Model

In [132]:
X = df_trainingset.drop('SalePrice', axis=1)
y = df_trainingset['SalePrice']

In [133]:
from sklearn.model_selection import train_test_split

Xtrain,Xtest,ytrain,ytest = train_test_split(X,y)

In [134]:
from sklearn.linear_model import LinearRegression

ml = LinearRegression()

In [135]:
ml.fit(Xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [136]:
print("R2 = ", ml.score(Xtest,ytest))

print('Coefs = ', ml.coef_)

print('Intercept =', ml.intercept_)

R2 =  0.8620310725495027
Coefs =  [ 6.41696247e+02  9.10913532e+03  1.12592914e+04 -1.89952096e+02
 -2.89724106e+02 -5.29102320e+03 -2.02710753e+02  1.40921586e+02
  3.00665590e+03  4.32842062e+03  1.54312263e+04 -2.73146335e+01
  8.66346366e+03  5.95555968e+01  9.66768290e+02  1.13111101e+02
  5.38389138e+02  2.93809649e+02 -9.02466536e+00  2.97188198e+03
  8.09837133e+03 -6.82041164e+03 -1.50811197e+02  1.10826225e+04
 -2.05218723e+03  4.85975407e+03  4.79785450e+04  3.90539688e+03
  3.80572987e+04  1.83291719e+04  1.10777959e+04  2.48974171e+04
 -1.39346304e+04  9.67645231e+03  5.24967800e+03  7.94692339e+03
 -3.27418093e-11 -4.78304819e+04  1.76970869e+04 -7.15023377e+03
  8.11141481e+04 -2.08618686e+03 -2.62719297e+04 -1.03619519e+04
 -5.06149075e+03  1.25587915e+04 -3.11987111e+03 -9.91510216e+03
 -8.00331211e+03  5.58214520e+03 -1.54740766e+04  3.87850698e+02
 -2.72587094e+04 -7.15023377e+03 -8.93321403e+04 -1.41368590e+04
 -1.87564983e+04 -1.77143239e+03 -1.75532477e-10 -1.8708

In [138]:
ml.predict(df_testingset)

array([121365.4228893 , 166127.58731406, 184132.0422014 , ...,
       194727.39524202, 113038.83455629, 218011.37162307])

In [139]:
len(list(ml.coef_))

115

# Ridge and Lasso

In [140]:
from sklearn.linear_model import Lasso, Ridge, ElasticNet

lasso = Lasso(tol = 0.001, max_iter = 100000)
ridge = Ridge()

In [141]:
#setting alpha values that we want to grid search 
params_lasso = [{'alpha': [1* 10**i for i in range(-2,3)]}]
params_ridge = [{'alpha': [1*10**i for i in range(-2,3)]}]

In [142]:
from sklearn.model_selection import GridSearchCV

grid_lasso = GridSearchCV(estimator = lasso, param_grid = params_lasso, cv=5)
grid_ridge = GridSearchCV(estimator = ridge, param_grid = params_ridge, cv=5)


In [143]:
grid_lasso.fit(X,y)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=100000, normalize=False, positive=False,
                             precompute=False, random_state=None,
                             selection='cyclic', tol=0.001, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid=[{'alpha': [0.01, 0.1, 1, 10, 100]}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [144]:
grid_ridge.fit(X,y)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=None, normalize=False, random_state=None,
                             solver='auto', tol=0.001),
             iid='warn', n_jobs=None,
             param_grid=[{'alpha': [0.01, 0.1, 1, 10, 100]}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [145]:
grid_lasso.best_score_

0.8743098233450451

In [146]:
grid_ridge.best_score_

0.8729633617816538

In [147]:
top_lasso = grid_lasso.best_estimator_

In [148]:
top_ridge = grid_ridge.best_estimator_

In [149]:
print('Lasso Test Score:', top_lasso.score(X,y))
print('Ridge Test Score:', top_ridge.score(X,y))

Lasso Test Score: 0.887369018620634
Ridge Test Score: 0.8886107750522363


In [150]:
top_lasso.get_params

<bound method BaseEstimator.get_params of Lasso(alpha=100, copy_X=True, fit_intercept=True, max_iter=100000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.001, warm_start=False)>

In [152]:
top_lasso.predict(df_testingset)

array([120809.81708312, 162083.89589264, 181028.368963  , ...,
       185563.08328951, 122052.86969422, 220189.3617443 ])

In [153]:
top_lasso.coef_

array([ 1.29528508e+02,  8.29551863e+03,  1.31566718e+04, -1.46546535e+02,
       -3.24695150e+02,  1.46134458e+02, -1.13879639e+02,  1.23581247e+02,
        6.70926443e+01,  2.54455420e+03,  1.65468280e+04,  1.82881654e+03,
        7.19460209e+03,  1.23801721e+01,  7.36123451e+02,  9.43495926e+01,
        6.02108189e+02,  2.19900865e+02,  6.31680199e+02,  1.72467115e+03,
        2.04662050e+03, -0.00000000e+00, -9.82977202e+02,  0.00000000e+00,
       -2.76123779e+03,  0.00000000e+00,  4.44285983e+04,  9.51096466e+03,
        3.25759487e+04,  2.08824700e+03,  1.17545561e+03,  0.00000000e+00,
       -8.73749230e+02,  2.94633563e+03, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  1.72473999e+04, -0.00000000e+00,
        1.08282349e+04, -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
       -6.51763959e+02,  0.00000000e+00,  1.00638051e+03, -6.44900278e+01,
       -1.90281039e+03,  0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -

In [154]:
top_ridge.coef_

array([   207.06412006,   8242.80639733,  13359.12125345,   -144.74063521,
         -315.44090772,    445.24252256,   -139.38161626,    126.7621664 ,
         7739.57925755,   4073.02774358,  11792.08553667,   1765.52110118,
         8169.37609021,     40.82649766,   2057.20716547,     94.31131469,
          636.86514295,    311.45602707,    578.5561572 ,   1796.91899026,
         4571.48036739,  -4411.40696039,  -1904.52463055,   2695.51356511,
        -4780.91238173,    288.46411078,  36290.11221488,   9906.43306629,
        26394.13682023,   8475.4659445 ,   4163.48545854,   7478.27156049,
        -6319.90408737,   4968.35340619,   -416.52653547,    747.41862805,
        -1023.42683466,  -4567.28932128,  14664.97914767,   -812.08435454,
         7515.43290591,  -2144.54118143,  -1790.9486371 ,  -1557.17563402,
        -3759.28510997,   2199.60327193,   2545.65815697,  -5033.57848346,
        -7387.67306937,   -422.47924152,  -1624.84500108,   -469.67479733,
        -2379.23727609,  

# ElasticNet

In [155]:
elastic = ElasticNet()

In [156]:
params_elastic = {'alpha': [1* 10**i for i in range(-2,3)],
                  'l1_ratio': [i/10 for i in range(1,10)]}
#parametersGrid = {"max_iter": [1, 5, 10],
                      #"alpha": [0.0001, 0.001, 0.01, 0.1, 1, 10, 100],
                      #"l1_ratio": np.arange(0.0, 1.0, 0.1)}

In [157]:
grid_elastic = GridSearchCV(estimator = elastic, param_grid = params_elastic, cv=5, verbose=1, scoring='r2')

In [158]:
grid_elastic.fit(X,y) #i/10 for i in range(1,10)

Fitting 5 folds for each of 45 candidates, totalling 225 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 225 out of 225 | elapsed:    4.0s finished


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True,
                                  l1_ratio=0.5, max_iter=1000, normalize=False,
                                  positive=False, precompute=False,
                                  random_state=None, selection='cyclic',
                                  tol=0.0001, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'alpha': [0.01, 0.1, 1, 10, 100],
                         'l1_ratio': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
                                      0.9]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='r2', verbose=1)

In [159]:
grid_elastic.best_score_

0.8738578996870598

In [160]:
top_elastic = grid_elastic.best_estimator_

In [161]:
top_elastic.score(X,y)

0.8906158917263287

In [162]:
grid_elastic.best_params_

{'alpha': 0.01, 'l1_ratio': 0.6}

### Predict and Save To .csv file

In [188]:
pred = top_lasso.predict(df_testingset)

In [189]:
p = pd.DataFrame(pred)

In [190]:
i = pd.DataFrame(test.index)

In [191]:
results = pd.concat([i, p], axis=1)
results.columns = ['Id', 'SalePrice']

In [192]:
results.reset_index(drop=True, inplace=True)


In [193]:
results.reset_index(drop=True, inplace=True)

In [194]:
results.to_csv('submission2_lasso.csv', index=False)